### ISSUE TITLE
While running FTB Pyramid 3.0 via the vanilla launcher Guide Book causes minecraft to lose focus

### ISSUE THREAD

**Issue by dazsim** [FTBTeam/FTB-Guides#16]
As title says, when right clicking book to open it, the game loses focus until escape is pressed.  I am running 1.8.0_172 Java (64-bit). Let me know if you need more info.
[latest.log](https://github.com/LatvianModder/FTBGuides/files/2368842/latest.log)

**Comment by LatvianModder** [comment]
I need the client log / log.gz file

**Comment by LatvianModder** [comment]
If you are using the vanilla/native launcher, it doesn't use your computer java, but its own, which is version _10 I belive

**Comment by dazsim** [comment]
I tried both launchers using the twitch client. log attached.  I also
updated java to the latest version and no difference.
